import fs from "node:fs";
import path from "node:path";
import { parse } from "yaml";
import type {
  Event,
  EventWithVenue,
  RawEvent,
  ResolvedScheduleItem,
  Speaker,
  Talk,
  Update,
  Venue,
} from "./types";

const dataDir = path.join(process.cwd(), "src", "data");

// ---------------------------------------------------------------------------
// Optimized image manifest (generated by scripts/optimize-images.ts)
// ---------------------------------------------------------------------------

interface ImageEntry {
  sm: string;
  lg: string;
}

type ImageManifest = Record<string, ImageEntry>;

let imageManifest: ImageManifest | null = null;

function getImageManifest(): ImageManifest {
  if (!imageManifest) {
    const manifestPath = path.join(dataDir, "image-manifest.json");
    try {
      imageManifest = JSON.parse(
        fs.readFileSync(manifestPath, "utf-8")
      ) as ImageManifest;
    } catch {
      imageManifest = {};
    }
  }
  return imageManifest;
}

// ---------------------------------------------------------------------------
// Module-level cache — YAML files are read once per build
// ---------------------------------------------------------------------------

let eventsCache: Event[] | null = null;
let speakersCache: Speaker[] | null = null;
let talksCache: Talk[] | null = null;
let venuesCache: Venue[] | null = null;
let updatesCache: Update[] | null = null;

function readYaml<T>(filename: string): T[] {
  const filePath = path.join(dataDir, filename);
  const content = fs.readFileSync(filePath, "utf-8");
  return parse(content) as T[];
}

function formatDate(dateStr: string): string {
  const d = new Date(dateStr);
  return d.toLocaleDateString("en-MY", {
    weekday: "short",
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
    hour12: true,
    timeZone: "Asia/Kuala_Lumpur",
  });
}

// ---------------------------------------------------------------------------
// Core accessors
// ---------------------------------------------------------------------------

export function getAllEvents(): Event[] {
  if (!eventsCache) {
    const raw = readYaml<RawEvent>("event.yml");
    eventsCache = raw.map((e) => ({
      ...e,
      dateStr: formatDate(e.date),
    }));
  }
  return eventsCache;
}

export function getEventByName(name: string): Event | undefined {
  return getAllEvents().find((e) => e.name === name);
}

export function getAllSpeakers(): Speaker[] {
  if (!speakersCache) {
    speakersCache = readYaml<Speaker>("speaker.yml");
  }
  return speakersCache;
}

export function getSpeakerById(id: string): Speaker | undefined {
  return getAllSpeakers().find((s) => s.id === id);
}

export function getAllTalks(): Talk[] {
  if (!talksCache) {
    talksCache = readYaml<Talk>("talk.yml");
  }
  return talksCache;
}

export function getTalkById(id: string): Talk | undefined {
  return getAllTalks().find((t) => t.id === id);
}

export function getAllVenues(): Venue[] {
  if (!venuesCache) {
    venuesCache = readYaml<Venue>("venue.yml");
  }
  return venuesCache;
}

export function getVenueById(id: string): Venue | undefined {
  return getAllVenues().find((v) => v.id === id);
}

export function getAllUpdates(): Update[] {
  if (!updatesCache) {
    updatesCache = readYaml<Update>("update.yml");
  }
  return updatesCache;
}

// ---------------------------------------------------------------------------
// Computed / derived functions
// ---------------------------------------------------------------------------

/**
 * Returns an optimized local image URL if available, otherwise falls back to
 * the original remote URL. The `size` parameter controls which variant to use:
 * - "sm" (default): 80x80 avatar
 * - "lg": 640x768 portrait
 */
export function getSpeakerImageUrl(
  speaker: Speaker,
  size: "sm" | "lg" = "sm"
): string | null {
  const manifest = getImageManifest();
  const entry = manifest[speaker.id];
  if (entry) return entry[size];

  // Fallback to unoptimized remote URL
  if (speaker.image) return speaker.image;
  if (speaker.github) return `https://github.com/${speaker.github}.png`;
  return null;
}

/** Collects unique speakers from an event's schedule talks. */
export function getSpeakersForEvent(event: Event): Speaker[] {
  if (!event.schedule) return [];

  const speakerIds = new Set<string>();

  for (const item of event.schedule) {
    if (item.type === "talk" && item.talk) {
      const talk = getTalkById(item.talk);
      if (talk) {
        for (const sid of talk.speakers) {
          speakerIds.add(sid);
        }
      }
    }
  }

  return [...speakerIds]
    .map((id) => getSpeakerById(id))
    .filter((s): s is Speaker => s !== undefined);
}

/** All talks where the speaker appears in the speakers array. */
export function getTalksForSpeaker(speakerId: string): Talk[] {
  return getAllTalks().filter((t) => t.speakers.includes(speakerId));
}

/** Events where type=workshop and instructor includes speaker. */
export function getWorkshopsForSpeaker(speakerId: string): Event[] {
  return getAllEvents().filter(
    (e) =>
      e.type === "workshop" &&
      Array.isArray(e.instructor) &&
      e.instructor.includes(speakerId)
  );
}

/** Events where type=webcast and instructor includes speaker. */
export function getWebcastsForSpeaker(speakerId: string): Event[] {
  return getAllEvents().filter(
    (e) =>
      e.type === "webcast" &&
      Array.isArray(e.instructor) &&
      e.instructor.includes(speakerId)
  );
}

/** Finds the event that contains a given talk in its schedule. */
export function getEventForTalk(talkId: string): Event | undefined {
  return getAllEvents().find(
    (e) =>
      Array.isArray(e.schedule) &&
      e.schedule.some((s) => s.type === "talk" && s.talk === talkId)
  );
}

/**
 * Resolves venue for an event.
 * If event has no `venue` property → "Online event".
 */
export function getVenueForEvent(
  event: Event
): { venueName: string; venue?: Venue } {
  if (!event.venue) {
    return { venueName: "Online event" };
  }
  const venue = getVenueById(event.venue);
  return {
    venueName: venue?.name ?? event.venue,
    venue,
  };
}

/** Filters updates belonging to a specific event. */
export function getUpdatesForEvent(eventName: string): Update[] {
  return getAllUpdates().filter((u) => u.meetupEvent === eventName);
}

// ---------------------------------------------------------------------------
// Higher-level helpers
// ---------------------------------------------------------------------------

/** Returns all events sorted by date descending (newest first). */
export function getAllEventsSorted(): Event[] {
  return [...getAllEvents()].sort(
    (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
  );
}

/** Returns the upcoming event (first event with date in the future), or null. */
export function getUpcomingEvent(): EventWithVenue | null {
  const now = new Date();
  const upcoming = getAllEvents()
    .filter((e) => new Date(e.date) > now)
    .sort(
      (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()
    )[0];

  if (!upcoming) return null;

  const { venueName, venue } = getVenueForEvent(upcoming);
  return { ...upcoming, venueName, venueData: venue };
}

/** Resolves schedule items with full talk and speaker data. */
export function getResolvedSchedule(event: Event): ResolvedScheduleItem[] {
  if (!event.schedule) return [];

  return event.schedule.map((item) => {
    if (item.type === "talk" && item.talk) {
      const talk = getTalkById(item.talk);
      if (talk) {
        const speakers = talk.speakers
          .map((id) => getSpeakerById(id))
          .filter((s): s is Speaker => s !== undefined);
        return {
          time: item.time,
          type: item.type,
          desc: item.desc,
          talk: { ...talk, speakers },
        };
      }
    }
    return { time: item.time, type: item.type, desc: item.desc };
  });
}

/** Resolves instructor IDs to Speaker objects. */
export function getInstructorsForEvent(event: Event): Speaker[] {
  if (!event.instructor) return [];
  return event.instructor
    .map((id) => getSpeakerById(id))
    .filter((s): s is Speaker => s !== undefined);
}

// ---------------------------------------------------------------------------
// Utility functions (replaces src/lib.js)
// ---------------------------------------------------------------------------

export function isFilledArray<T>(array: T[] | undefined | null): array is T[] {
  return Array.isArray(array) && array.length > 0;
}

export function pluralize(singular: string, count: number): string {
  return count > 1 ? `${singular}s` : singular;
}

export function groupBy<T>(
  array: T[],
  getKey: (item: T) => string
): [string, T[]][] {
  if (!isFilledArray(array)) return [];

  const resultByKey: Record<string, T[]> = {};

  for (const item of array) {
    const key = getKey(item);
    if (resultByKey[key]) {
      resultByKey[key].push(item);
    } else {
      resultByKey[key] = [item];
    }
  }

  return Object.keys(resultByKey).map((key) => [key, resultByKey[key]]);
}

export function titleCase(value: string): string {
  if (!value) return value;
  return value[0].toUpperCase() + value.substring(1).toLowerCase();
}
